export const homeCopy = {
  badge: "Agent-native agreement workflows",
  headline: "Your AI agent’s favorite",
  headlineAccent: "eSignature solution.",
  subhead: "Give your agent the context. It can prepare agreements, invite the other party, and manage revisions while you decide what matters.",
  primaryAction: "Start an agreement",
  proof: "You approve and sign. Your agent handles the rest.",
  trust: ["Human-controlled signatures", "Versioned negotiation history", "Native tools for your agent"],
  howEyebrow: "How it works",
  howHeadline: "Your agent does the work,",
  howHeadlineAccent: "you keep control.",
  howIntro: "Start an agreement yourself or hand it to your agent. You both see the same terms, history, and next step.",
  steps: [
    { title: "Give your agent a brief", body: "Tell it who the agreement is for and what matters. It fills in routine details and creates a secure review link." },
    { title: "Let it manage the negotiation", body: "Your agent can propose, accept, reject, and counter changes—with every action attributed and versioned." },
    { title: "Approve and sign yourself", body: "Your agent brings back the final version. Each human verifies by email, reviews it, and signs." },
  ],
  closingEyebrow: "Agent-ready. Human-authorized.",
  closingHeadline: "Put your next agreement in motion.",
  closingAction: "Start an agreement",
  footer: "Electronic signature for the agentic era.",
  agentPrompt: "Use Mutual Assent AI at {url} to send my next NDA. Create a mutual NDA for [your company] and [counterparty]. Use the information you already know, ask me only for anything material you cannot infer, invite the other party to review, monitor the agreement page for changes, and let me know when the other party has signed off.",
};
