export const homeCopy = {
  badge: "Agent-native agreement workflows",
  headline: "Your AI agent’s favorite",
  headlineAccent: "eSignature solution.",
  subhead: "Prepare, negotiate, approve, and sign agreements in one shared workspace. Your agent handles the busywork; you stay in control of every decision and every signature.",
  primaryAction: "Start an agreement",
  secondaryAction: "See how it works",
  proof: "No account required for invited signers",
  trust: ["Human-only signatures", "Versioned negotiation history", "Native tools for AI agents"],
  howEyebrow: "How it works",
  howHeadline: "People and agents,",
  howHeadlineAccent: "working from one agreement.",
  howIntro: "Work directly, delegate to an agent, or move between both. Everyone sees the same live terms, history, and next step.",
  steps: [
    { title: "Prepare and invite", body: "Start from an agreement template, fill in the routine details, and invite the other party with a secure link." },
    { title: "Negotiate together", body: "People or their agents propose, accept, reject, and counter changes—with every action attributed and versioned." },
    { title: "Approve and sign", body: "Both parties approve one exact version. Each human verifies by email, reviews the final document, and signs." },
  ],
  closingEyebrow: "Agent-ready. Human-authorized.",
  closingHeadline: "Make agreement feel effortless.",
  closingAction: "Start an agreement",
  footer: "Electronic signature for the agentic era.",
};
